# Standard Rounding Demonstration

There is not much to discuss in this section. This exists mostly to compare to other rounding options. Standard rounding is deterministic and so not unbiased, and has no significant properties other than being fast.

In [1]:
from dependent_rounding import round_matrix
import numpy as np

m=4000
n=4000
np.set_printoptions(precision=3)
np.set_printoptions(suppress=True)

start = np.abs(np.random.normal(0,0.5,(m,n)))
print(start)

[[0.403 0.292 0.603 ... 0.542 0.84  0.225]
 [1.357 0.285 0.227 ... 0.22  0.14  0.371]
 [0.344 0.    0.369 ... 0.101 0.231 0.316]
 ...
 [0.232 0.016 0.003 ... 0.238 0.328 0.31 ]
 [0.754 0.304 0.38  ... 0.01  1.31  0.144]
 [0.059 0.143 0.759 ... 0.01  0.026 0.271]]


### Timing Comparison


In [2]:
python_result = round_matrix(np.copy(start), 'standard', 0, 'python', track_time=True)

Total time (ms): 170.4728603363037


In [3]:
cpp_result = round_matrix(np.copy(start), 'standard', 0, 'cpp', track_time=True)

Total time (ms): 112.49494552612305


In [4]:
np.max(cpp_result - python_result)

0.0